"""empty message

Revision ID: 05b25f1adb2d
Revises: 880e3973f248
Create Date: 2025-07-07 18:47:59.992663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b25f1adb2d'
down_revision = '880e3973f248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('birth_year')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('terrain')
        batch_op.drop_column('population')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
